source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HardCoreData', :exclusive => true do
  pod "HardCoreData", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "HardCoreData", :path => "../"
  pod "Expecta"
  pod "OCMock"

end
